import React from 'react';
import ReactDOM from 'react-dom/client';
import { Amplify } from 'aws-amplify';
import outputs from '../amplify_outputs.json';
import App from './App';
import './index.css';

/**
 * amplify_outputs.json is auto-generated by `npx ampx sandbox`
 * or `npx ampx pipeline-deploy`. It contains the Cognito User Pool ID,
 * AppSync endpoint, and all other backend configuration.
 *
 * Never commit this file — it's environment-specific.
 * Add amplify_outputs.json to .gitignore.
 */
Amplify.configure(outputs);

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
